### ISSUE TITLE
No Price available

### ISSUE THREAD

**Issue by AquaMCU** [Jhruzik/finanzen-fundamentals#11]
Hi. Seems the API has changed. Since about a week , I get the below error message.

<SNIP>
File "/home/oliver/.config/libreoffice/4/user/Scripts/python/test.py", line 5, in <module>
    a = stocks.get_price(stock=stock_id, exchange="FSE", output="dict")
  File "/home/oliver/.local/lib/python3.9/site-packages/finanzen_fundamentals/stocks.py", line 200, in get_price
    raise NoDataException("No price available")
finanzen_fundamentals.exceptions.NoDataException: No price available
</SNIP>

Here the code I use:
import finanzen_fundamentals.stocks as stocks

stock_id = "kellogg-aktie"

a = stocks.get_price(stock=stock_id, exchange="FSE", output="dict")
print ( a.get("Price") )

**Comment by AquaMCU** [comment]
BTW I have pip installed version 0.3.1

pip3 show finanzen-fundamentals
Name: finanzen-fundamentals
Version: 0.3.1

**Comment by Jhruzik** [comment]
Thanks for bringing that up. Looks like Finanzen changed the HTML code a bit. Doesn't look complicated, I'll make the adjustments this tomorrow or this weekend.

**Comment by Jhruzik** [comment]
Just uploaded a new version to pypi and it should work now. Also, I noticed some changes in the date field, so I fixed that as well.

**Comment by AquaMCU** [comment]
Works perfect! Thank you. You can close this ticket if you want

BTW: Here is a Libreoffice Wrapper I am using:

1. Install the Python Sctipt Package for Libreoffice
2. Copy the file to ~/.config/libreoffice/4/user/Scripts/python

---
import finanzen_fundamentals.stocks as stocks
  def getprice(stock_id):
  a = stocks.get_price(stock=stock_id, exchange="FSE", output="dict")
  return a.get("Price")
g_exportedScripts = (getprice,)
---

Schönes Wochenende!
