### ISSUE TITLE
Wrong dependency in setup.py

### ISSUE THREAD

**Issue by bkircher** [Jhruzik/finanzen-fundamentals#14]
Installing with setup.py and pip installs a wrong dependency.

```raw
pip install finanzen-fundamentals
Collecting finanzen-fundamentals
  Downloading finanzen_fundamentals-0.3.2-py3-none-any.whl (19 kB)
Requirement already satisfied: requests in ./.venv/lib/python3.11/site-packages (from finanzen-fundamentals) (2.28.2)
Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
  ```
  
  This line
  https://github.com/Jhruzik/finanzen-fundamentals/blob/1d62485dd818e12bc42db66c09a53284555ca2bf/setup.py#L16

should include `"beautifulsoup4"` instead of `"bs4"`.

**Comment by Jhruzik** [comment]
True, I will fix this bug together with the larger overall functionality bug in issue #13

**Comment by Jhruzik** [comment]
Fixed :)
