### ISSUE TITLE
AttributeError on Swiss Funds (CHF)

### ISSUE THREAD

**Issue by 82409** [Jhruzik/finanzen-fundamentals#16]
Hello.

I'm encountering a problem when trying to retrieve Swiss funds, other funds seems to work fine.
This is the error message that I'm getting, when trying `funds.get_info("akb-portfoliofonds-akb-einkommen-esg-fokus-a-ch0395074641")`:

```
AttributeError                            Traceback (most recent call last)
Cell In [57], line 1
----> 1 funds.get_info("akb-portfoliofonds-akb-einkommen-esg-fokus-a-ch0395074641")

File ~/.local/lib/python3.10/site-packages/finanzen_fundamentals/funds.py:50, in get_info(fund, output)
     45     isin = None
     47 ## Find Fundamentals
     48 ### Find Base Table
     49 table_base = soup.find("h2", {"class": "box-headline"},
---> 50                        string="Wichtige Kennzahlen").parent
     51 table_rows = table_base.find_all("tr")
     53 ### Define Function to Extract Row

AttributeError: 'NoneType' object has no attribute 'parent'
```

Thanks for the great library!

Best regards,

Nick

**Comment by 82409** [comment]
Hi Joshua, my apologies, I just realised that it's on finanzen.ch and not finanzen.net
This was the fund that I was looking: https://www.finanzen.ch/fonds/akb-portfoliofonds-akb-einkommen-esg-fokus-a-ch0395074641

**Comment by Jhruzik** [comment]
Thanks for getting back to me. It doesn't seem that this fund is under finanzen.net except for some price quotes (https://www.finanzen.net/kurse/ch0395074641). Hence, I am closing the ticket.
