### ISSUE TITLE
Unexpected sign on float parsing in function get_current_value_lxml

### ISSUE THREAD

**Issue by paulwuertz** [Jhruzik/finanzen-fundamentals#2]
Hej, I am using your library to show some data on an e-paper display with refreshing once a day, thank you for your work.

Sometimes an error gets thrown, cause the string you get from 'chg_to_open' is  "±0.00", which can not be parsed to float. (see the stack trace I get from below). Replacing the "±" helps, I'll send in a PR.

Thanks for your work!
Paul

```
Traceback (most recent call last):
  File "script.py", line XX, in <module>
    val = ff.get_current_value_lxml(name)
  File ".../lib/python3.6/site-packages/finanzen_fundamentals/stocks.py", line 351, in get_current_value_lxml
    float(raw_change[0].replace(',', '.')),
ValueError: could not convert string to float: '±0.00'

```

**Comment by Jhruzik** [comment]
Pull Request was merged and package has been updated on PyPi.
