### ISSUE TITLE
No return for key ratio

### ISSUE THREAD

**Issue by M3rXy** [Jhruzik/finanzen-fundamentals#9]
Hello there,

I am really enjoying that library and I use it to perform a fundamental analysis. It works very well for most stocks. 
But there are some known stocks which raise an error while importing. Two examples are "Moderna", ticker: MRNA and "Gartner Inc." ticker: IT. In both cases the error occurs for the "key ratios". If you look up the stocks they have both the following in common: at some point in time their equity was below 0. This happens also for McDonalds.
 
<img width="1000" alt="Gatner" src="https://user-images.githubusercontent.com/45830917/130370096-7d15c30a-454d-4536-a2de-d8d39262397b.png">
<img width="994" alt="Moderna" src="https://user-images.githubusercontent.com/45830917/130370098-5e2f44fe-2811-4500-bb8c-f20940025776.png">

I can't say if this is really the issue, but its my best guess as all of them have the same structure of a "0<*".

I would really appreciate if you could fix that bug. 

Best regards

**Comment by Jhruzik** [comment]
Hello,

thanks for raising that issue. I was not aware of such cases. I fixed it and just released V 0.2 with some additional features.

Thank you
Joshua
